### ISSUE TITLE
meeting times

### ISSUE THREAD

**Issue by lmcneil7** [lmcneil7/teen-titans#1]
cool since it's just you and me @smdunn921 , when do you want to meet up during the week to do this? we can have a set time each week to just meet up and discuss the project or we can set time every other week to have a work session? i don't know, what are you feeling?

**Comment by smdunn921** [comment]
I'm free MWF before 1p and after 4p; T/Th I'm free after 5:30. We might want to stick to every week rather than every other just because there will be a good bit to do and there's just us.

**Comment by lmcneil7** [comment]
I'm free MF after 9:10a until 3p; W I'm not free until 1p. For T/Th I'm free before 1p and after 4p. I was thinking every week is a good idea too. I'm more inclined to working at night if you're more willing to do so. I have theater rehearsal at 7:00p-8:30p. If you want to stick to during the day, I think we could do 11p-1p on M/F or 5:30p-7p on T/Th.

**Comment by smdunn921** [comment]
We might even be able to take it week by week in case one of us can't do the selected time one week. I'm good with working later in the day and think that 5:30-7p on T/Th would be ideal.
