### ISSUE TITLE
Team Meeting

### ISSUE THREAD

**Issue by alnopa9** [lmcneil7/teen-titans#11]
Hey Teen Titans team!
So, Dr. B announced in class on Friday how we're trying to meet up with teams to make sure everything is going smoothly for project teams. I was wondering what time next week would work for the both of you? I am free most afternoons.
Hope to hear back!
@lmcneil7 @smdunn921

**Comment by lmcneil7** [comment]
I'm free after 4pm on most afternoons except for Wednesday. As for mornings, I can't do Tuesday or Thursday and MWF I have a period between 9:20am-3:00pm that I'm free except for Wednesday.

**Comment by smdunn921** [comment]
I'm super busy on Tuesdays and Thursdays but I'm available MWF between 2-3 or after 4
