### ISSUE TITLE
Team Meeting Recap

### ISSUE THREAD

**Issue by alnopa9** [lmcneil7/teen-titans#12]
Hey Teen Titans team,
So, I added back in your markup that I had stripped out in my earlier push. Here's the [commit](https://github.com/lmcneil7/teen-titans/commit/614f2d69d61a76f89b33ca6c738147c663a4983b#diff-51018cc0dc915098e43ee79234593e90)

I also did an example markup for Issue 1 of the comic. [commit](https://github.com/lmcneil7/teen-titans/commit/4027afaa2927ed7e4319eb4b717f15a0d8bd67de)
There's a good bit of metadata in it.
  - I have the whole team that worked on the comic listed in the `<head>` element
  - A list of characters in the comic in order of appearance
  - A breakdown of the different settings in the comic as well as which characters appear in each
  - A list of references made by the characters that are part of DC lore

I also wrote a separate schema for the comic markup since it's different than what you're marking up for the television series.

Hope this helps!
Alyssa

**Comment by smdunn921** [comment]
This is wonderful thank you so much!!

**Comment by alnopa9** [comment]
I also marked up episode 2 for you guys, but I didn't go in depth with the `<sd>` like you guys have been. Feel free to add markup to it.
