### ISSUE TITLE
student suggestions

### ISSUE THREAD

**Issue by bobbyfunks** [lmcneil7/teen-titans#17]
I thought the idea of comparing the comic to the show was very interesting.  That's def a challenge since there is lots of material.  My suggestion for the site would be more pics definitely but maybe include a bio page for each character or a history page for teen titans in general, that would be cool.  But the idea of having the comic version on one side and the show script on the other was great.

**Comment by cozyycoding** [comment]
i loved the presentation, I really like the idea of being able to compare the episodes of the show with the comics they're based off of. My main suggestions would be to add more pictures of the comics in the comparison and to maybe highlight some of the text in the tv show where it differs strongly from the comics.
