### ISSUE TITLE
Ready for Grading !

### ISSUE THREAD

**Issue by lmcneil7** [lmcneil7/teen-titans#18]
Hey! We finish the website, and it's ready to be graded. Thank you guys for the help and have a wonderful break. @ebeshero @alnopa9 @KSD32

**Comment by ebeshero** [comment]
@lmcneil7 @smdunn921 I've posted some detailed comments to review the Teen Titans project here in your repo: https://github.com/lmcneil7/teen-titans/blob/master/teentitansEvaluation-12-2019.md  Congratulations on a wonderful project, and we hope you'll continue building on the strong foundation you have here! 

@alnopa9 @KSD32
