### ISSUE TITLE
XML Exercise 1 - Shannon Dunn 

### ISSUE THREAD

**Issue by frabbitry** [lmcneil7/teen-titans#20]
@smdunn921 

Good work on XML exercise one! The colors used to highlight the character spans in conjunction with the Javascript on the "Texts" section of the website work well against the black background of the website; they're noticeable without being jarring. 

Graphic design is one of my favorite parts of building a website because it's very artistic and creative. Having a keen sense of color, style, and composition can really transform a website from a mere presentation of information into something that captivates users and draws them in. Having a unified color scheme can help to make the website user feel like every page on a website is part of the same experience, so I like that the colors used to highlight sections of the texts are used throughout the website. 

Going with the dark background is bold, and I like it. The "dark theme" has definitely become a very important facet of web design, and it helps your website to stand out. I'm going to point you to [this](https://uxplanet.org/8-tips-for-dark-theme-design-8dfc2f8f7ab6) resource for some tips on how to design a website with a darker color scheme, and I'd emphasize the points about opting for a dark gray rather than a strict black background and about tinkering with the opacity or saturation of the colors to ensure that your website is as readable as possible. If you go [here,](https://www.tedmontgomery.com/tutorial/clrctgBL.html) you can see a bunch of different colors against a black background. A lot of these colors are pretty jarring -- some even seem to vibrate on the page -- but they could be made more visually appealing by both changing the hue of the background to more of a dark gray than black and by altering the opacity and/or saturation of the colors. The colors should have an opacity of less than 100% (usually from 60-87%) and be lighter hues (in the 200-50 range). Spotify is an excellent example of a website (/app, desktop application, etc.) that utilizes a dark gray background. 

Moreover, adjusting the [CSS letter-spacing property](https://www.w3schools.com/cssref/pr_text_letter-spacing.asp) does a lot for readability, regardless of colors. [This](https://css-tricks.com/keeping-track-letter-spacing-guidelines/) web page has some good advice about how and why to mess with this property (and it also includes some history on the subject, which I think is kind of cool). 

Feel free to ping me with any questions or comments. Hope that gives you an idea of how to keep improving the website with CSS!

**Comment by ebeshero** [comment]
This is terrific advice–thank you, @frabbitry ! Taking a deep dive into CSS is well worth the effort now that we have more time to develop the project.
