### ISSUE TITLE
teen titans v.2 (meeting times, etc.)

### ISSUE THREAD

**Issue by lmcneil7** [lmcneil7/teen-titans#21]
We're back for round 2! I'm so excited to be working on this project again alongside Shannon. **Also, Welcome Amber!** We couldn't be more thrilled to have you.

### Meeting Times
While we didn't necessarily have a meeting time last semester because Shannon and I spent most of our time together anyway, it's necessary this semester. I'm thinking of the period before class (12:30ish-2:00) on Monday since all three of us tend to be in chambers at that time. If not, then, feel free to suggest other times! @frabbitry Since you're our project advisor, make sure to let us know a good time too. If we come to a scheduling problem, we can try a shorter meeting and work mostly with slack.

### GitHub
I sent invitations to Fiona and Amber, so we should be right on that. I want to add Brad so that all senior advisors/professors have access just in case they need it, but I don't know his username. I also closed the issues from last semester to restart the repo as if it was new. Similar to last time, I'll have a project going in Github and do checkpoint issues to indicate what we need to do or don't need to do. I'm hoping to use Github more for the organization, but also to have a good conversation going.

### Research question
Later this week, I'll have a more detailed description of what I'm envisioning for the project this semester. I'll post an issue so that we can discuss it! Any ideas are appreciated. 

### LASTLY>>>
```Unmasking the Teen Titans```
note: this is just a weekly event to clean the site up from last semester. I don't think there's much to do; we don't want to go back and try to redo previous semester's work later on. (for example: putting up comic XML that wasn't associated with the episodes, comments from grading, etc.)

**Comment by ebeshero** [comment]
Brad's GitHub handle is BMT45
:  https://github.com/bmt45 !

**Comment by lmcneil7** [comment]
Thank you! @ebeshero

**Comment by ebeshero** [comment]
Also, hooray for you (continuing) to use GitHub Projects!

**Comment by frabbitry** [comment]
@lmcneil7 so I'm in the Writing Center from 12-1 on Mondays, but I could meet from 1-2.

**Comment by smdunn921** [comment]
that works for me!

**Comment by amberpeddicord** [comment]
1-2 on Mondays works for me as well!

**Comment by lmcneil7** [comment]
Awesauce! I just realized we didn't decide on a location.

**Comment by smdunn921** [comment]
i know we usually sit in chambers beforehand, but do we think that this will be too loud/chaotic or do we want to *try* sticking with that?

**Comment by lmcneil7** [comment]
I was thinking about chambers, but Dr. B did mention _Brand New_ using the DH Tech Hub thingie, and I was wondering if we wanted to do that instead.

**Comment by amberpeddicord** [comment]
I'm good with using the Center if it's available. And there's a white board and some DH textbooks and stuff in there that we can use!

**Comment by amberpeddicord** [comment]
Also I've been getting email notifications for...my own replies? So that's fun

**Comment by smdunn921** [comment]
i know the office hours listed brad being in there til 1pm on mondays, so if that stays the same we can just snag it right after him if possible

**Comment by frabbitry** [comment]
I can unlock it for y'all 

Brad says he might still be chillin' in there but he doesn't care if we're in there.

**Comment by smdunn921** [comment]
ooh cool an hour of talking about teen titans and mildly harassing brad. count me in!

**Comment by amberpeddicord** [comment]
this is a test to see if i get an email for this reply

**Comment by amberpeddicord** [comment]
okay it worked, perfect!

**Comment by lmcneil7** [comment]
### MEETING TIME: 1:00pm-2:00pm @ CENTER
