### ISSUE TITLE
Beginning Markup

### ISSUE THREAD

**Issue by amberpeddicord** [lmcneil7/teen-titans#30]
@lmcneil7 @smdunn921 I'm opening this issue in case I have questions while doing markup! (I'll try not to read too closely and spoil the whole show for myself...)

I have one small question, though. For the metadata about the writers, directors, etc., is the info on the Teen Titans wiki accurate? I followed the link that @smdunn921 marked as the source information, so should I just use that information or find it somewhere else?

**Comment by lmcneil7** [comment]
I would say the info on the wiki is accurate since I also tend to use it for the metadata. If you find it there, then go for it!

**Comment by amberpeddicord** [comment]
@lmcneil7 Sick, thank you!

**Comment by smdunn921** [comment]
The info on the wiki pages should be correct. for the episodes that didn't have anything on the page i just googled the season and episode and looked there!
