### ISSUE TITLE
schematron suggestions

### ISSUE THREAD

**Issue by lmcneil7** [lmcneil7/teen-titans#42]
Time for some Schematron Suggestions! Sorry, this is late, but every time I decided I'm going to write it, I doze off for a lot more hours than I would like to. ANYWAY, I have some, and then we gained more ideas based on the meeting on Mar 02, so let's go! _ I'm going to assign the instructors as they are the experts in Schematron!_

**_Schematron Ideas:_**
- A way to count `@move` attribute (@amberpeddicord)
    - you don't have to scroll back to look up something; to check nodes and give you info about them
    - to keep track of them so we don't accidentally number two actions with one number
for instance:
```xml
<action mrkr="BeastBoy" with="none" move="2" place="park"/>
<action mrkr="BeastBoy" with="none" move="2" place="ship"/>
```
This is what we want to avoid without having to scroll up constantly.
- lat and long coordinates
    - This idea might be harder to implement but to make sure the coordinates match the place every time used in the XML.
- consistency of the `char` tag
    - making sure that each char matches another char if the name shows up twice.
for instance:
```xml
<char>the Master</char>
versus
<char>Master</char>
```
- spelling errors
for example: `"Starfir" versus "Starfire"`
- nicknames are indicated as the person if they're marked
for instance:
```xml
<char ref="Starfire">Star</char>
versus
<char>Star</char>
```
- consistency among our different marking styles
    - meaning small things like whether we're all tagging Jump City as location or not
    - do you leave the article ('the') in the tag? do you leave the punctuation('.') in the element?
- the `id` attribute on `<locList>` isn't the same unless the text is the same
    - meaning that we shouldn't have replicate ids unless it's the same location
for instance:
```xml
<locList id="tower">Titans' Tower</locList>
would be fine among all the episodes if it matched, but avoid a situation like this
<locList id="park">The Park</locList>
<locList id="park">A Park in Jump City</locList>
or even
<locList id="bay">Jump City Bay</locList>
<locList id="Bay">Jump City Bay</locList>
<locList id="bayofjc">Jump City Bay</locList>
```
This way, if we have different locations, but the same id, we can change them, so that's not a problem. Or, we have the same location but different ids. So we can either change the text to match or the id to match, so it's the same throughout all episodes. The example I used, the park versus a park, Schematron could also help us question if we're talking about the same location.
- time stamps
    - to avoid giving the same timestamp to a character twice in one episode
    - etc. (there's more Schematron could help us with this, but I'm not sure what)
- _Any ideas?_ (@instructors) I think I touched on the things that seem pressing with our XML, but please let us know if you noticed something else that might be helpful to point out.

**_Schematron (For Season 1)_**
We noticed problems with our XML from season 1, which definitely could have benefitted from Schematron. At the moment, it's focusing on the issues with `char` tag like spelling errors and consistency. We're going to want to look into creating a Schematron for season 1 as well.

Thank you! That's all for now, and I'm looking forward to the help that you guys can give us!

**Comment by lmcneil7** [comment]
Another thing we could include in Schematron is the difference between Robin and Raven for the `with` attribute. 
```xml
<... with="RB"/>
<... with="R"/>
```
I keep wanting to use R for both of them and have mostly noticed when I made that mistake, but Schematron could help keep that in check.

**Comment by ebeshero** [comment]
@lmcneil7 @amberpeddicord @smdunn921 @frabbitry You all probably want this sooner rather than later (like, I'm thinking before the code sprint of Spring Break). I'm free after class today if one of you wants to sit down with me and crank this out together!

**Comment by frabbitry** [comment]
@ebeshero Unfortunately, I will not be able to join in on a Schematron party after class today. I will be tutoring some Java students. Happy coding, though!

**Comment by amberpeddicord** [comment]
@ebeshero I should be able to stay after class today!

**Comment by lmcneil7** [comment]
@ebeshero I cannot stay after class because of my 3 pm! It's going suck to miss, but keep me posted about what you do!

**Comment by ebeshero** [comment]
@lmcneil7 @smdunn921 @frabbitry  Update! @amberpeddicord and I have prepared a super awesome wonderful Schematron that checks lots of things on the `<action>` elements. It will check for:

1) `@move` attributes and report (after you enter any old number as the value) what the immediately preceding value was for a given `@mrkr`. It will both issue a report and deliver an error when you enter the same value as the first preceding `<action> ` with the same `@mrkr`

2) whether you've accidentally mixed up location values for character values in the `@mrkr` and `@place` attributes.

 @amberpeddicord will continue on to prepare this Schematron to check for reasonably correct latitude and longitude coordinates should you begin messing with overlaying the world of Teen Titans on a map of San Francisco (or some other location). She will begin by reviewing [Schematron Exercise 1](https://dh.newtfire.org/).

**Comment by ebeshero** [comment]
All: I meant to include this: Here's the commit in which I pushed the Schematron to your rep:
https://github.com/lmcneil7/teen-titans/commit/8c193afe76e08682232f53a8e993d1b1cff65e94

And it's here in the repo file structure: https://github.com/lmcneil7/teen-titans/blob/master/xml/tv/tv-schematron.sch
