### ISSUE TITLE
Project Checkpoint #2

### ISSUE THREAD

**Issue by alnopa9** [lmcneil7/teen-titans#5]
# Project Checkpoint 2:
- [x] Locate all sources for project XML markup.
- [x] Establish a clear file directory structure on your project GitHub, including a distinct directory for website files.
- [x] Ensure all project team members are working consistently with the GitHub directory structure (all agree on it, and no one changes without notice).
- [x] Start work on a project schema (Relax NG or TEI): planning stage.
- [x] A significant quantity of project documentation and/or markup is present in the GitHub repo.

## Locate all sources for project XML markup.
You found a decent [source](https://transcripts.fandom.com/wiki/Teen_Titans) to use to get your text for markup! The next thing I would do is to have the raw text files saved in your repo.

## Establish a clear file directory structure on your project GitHub, including a distinct directory for website files.
Although we don't have a lot in the repo yet, the file management is well done. I like that you included an 'images' file in your site directory! You also made a 'seasonOne' directory for your XML that will allow you to include the other four seasons if you chose to. I would move your schema file to its own directory or move it out of the `seasonOne` file.
  - `teen-titans/XML/teenTitan.rnc`

## Ensure all project team members are working consistently with the GitHub directory structure (all agree on it, and no one changes without notice).
Looking at the [contributors page](https://github.com/lmcneil7/teen-titans/graphs/contributors) we can see that both members have been pushing to the repo! Great job!

## Start work on a project schema (Relax NG or TEI): planning stage.
Your [schema](https://github.com/lmcneil7/teen-titans/blob/master/XML/seasonOne/teenTitan.rnc) is off to a good start! This is just the planning phase, but your schema looks robust. As you markup more files, you'll get a better idea of what you want to include.

## A significant quantity of project documentation and/or markup is present in the GitHub repo.
There are only three XML files, [example of one](https://github.com/lmcneil7/teen-titans/blob/master/XML/seasonOne/episodeOne.xml), that are marked up, but the markup looks very well done and in depth.

**Comment by ebeshero** [comment]
Great work on Project Checkpoint 2, team!
