### ISSUE TITLE
Character Speech Graph for *WHOLE* Season?

### ISSUE THREAD

**Issue by smdunn921** [lmcneil7/teen-titans#52]
So I was looking at the SVGs for character speech counts per episode and started thinking about having 2 big SVGs to see who talked the most *overall* for each season, but I can feel my brain shutting off and i don't even know where to start and am asking for assistance. @ebeshero since you helped make the XSLT for single episode graphs last semester do you want to try your hand with this?

**Comment by ebeshero** [comment]
@smdunn921 I don't want your brains to be shutting down, and I'd like to help you, so I'm hoping I can help get you started! And your teammates should be involved, too, since they know the code better than I do at this point...How can we get this moving? @amberpeddicord has some good XQuery pulling some of those counts, I think. . .

**Comment by amberpeddicord** [comment]
@smdunn921 @ebeshero The XQuery that I made for the networks pulls speech counts for each Titan, so it might work if we adjust that code a little bit! Here are the links to the code on the GitHub, but they have the same names in the eXide directory as well.

[speakerNetwork_s1.xql](https://github.com/lmcneil7/teen-titans/blob/master/xquery/speakerNetwork_s1.xql)

[speakerNetwork_s2.xql](https://github.com/lmcneil7/teen-titans/blob/master/xquery/speakerNetwork_s2.xql)

**Comment by smdunn921** [comment]
thank you!!  i'm toying with adjustments,taking out the count mention things, and adding slade (and terra for season 2) because on the individual graphs they talk the most a handful of times and we can go from there. i have two animals and a full cup of coffee in the room so i'll get to workin
