### ISSUE TITLE
Updated index.html won't transfer in filezilla (but everything else will?)

### ISSUE THREAD

**Issue by smdunn921** [lmcneil7/teen-titans#7]
Okay so filezilla is letting me post up the new html pages (i.e. the about.html and texts.html) and the css style page, but when I go to try to move the newly updated index.html into the folder, filezilla yells at me (even though I said it can overwrite the old one) and the transfer fails

**Comment by ebeshero** [comment]
@smdunn921 I think the problem here is that @lmcneil7 technically "owns" the index.html file and the SFTP process isn't letting you overwrite what's there. The way to deal with this is easy: Delete the index.html (you're actually allowed to do that), and then upload your file in its place.

**Comment by ebeshero** [comment]
@smdunn921 let me know if that works, okay?

**Comment by smdunn921** [comment]
@ebeshero looks like it worked! Thank you lots-- I thought about that but didn't know if I was allowed

**Comment by ebeshero** [comment]
@smdunn921 Good! (And yes, definitely allowed. You'll probably have to delete a file on the server to replace it again, if each of you posts and updates files on the site, so keep this in mind.) That's actually a good opportunity to think about what makes GitHub less brittle than SFTP to a web server. You deleted that old index.html file and it went away on the web server, entirely--there's no easy way to get it back. But at least on GitHub we can access a file's detailed revision history. Always remember to post your web files on GitHub in case of catastrophe on the web server.
